name = "bom-api-cache"
main = "src/index.ts"
compatibility_date = "2025-09-15"

[vars]
# Allow your Vercel domain and local dev
CORS_ORIGIN = "https://floodfighter.vercel.app, http://localhost:3000"

# Upstreams (BOM ArcGIS)
UPSTREAM_FLOOD = "https://hosting.wsapi.cloud.bom.gov.au/arcgis/rest/services/flood/National_Flood_Gauge_Network/FeatureServer/1/query"
UPSTREAM_WATER = "https://hosting.wsapi.cloud.bom.gov.au/arcgis/rest/services/Australia_Water_Storages/MapServer/0/query"

# Cache TTL in seconds
CACHE_TTL = "3600"
